import { Position } from "@xyflow/react";

export const initialNodes = [
  {
    id: "n1",
    position: { x: 60, y: 140 },
    data: {
      label: "Computer",
      className: "nodeContent--main",
      style: { minWidth: 160 },
      handles: [{ id: "out", type: "source", position: Position.Right }],
    },
    type: "customNode",
  },
  {
    id: "n2",
    position: { x: 400, y: 140 },
    data: {
      label: "Electric Circuits",
      className: "nodeContent--main",
      style: { minWidth: 200 },
      handles: [
        { id: "in", type: "target", position: Position.Left },
        { id: "outTop", type: "source", position: Position.Right, offset: -40 },
        { id: "outBottom", type: "source", position: Position.Right, offset: 40 },
      ],
    },
    type: "customNode",
  },
  {
    id: "n3",
    position: { x: 740, y: 60 },
    data: {
      label: "CLOSED (ON)",
      className: "nodeContent--branch",
      style: { minWidth: 180 },
      handles: [
        { id: "in", type: "target", position: Position.Left },
        { id: "out", type: "source", position: Position.Right },
      ],
    },
    type: "customNode",
  },
  {
    id: "n4",
    position: { x: 740, y: 230 },
    data: {
      label: "OPEN (OFF)",
      className: "nodeContent--branch",
      style: { minWidth: 180 },
      handles: [
        { id: "in", type: "target", position: Position.Left },
        { id: "out", type: "source", position: Position.Right },
      ],
    },
    type: "customNode",
  },
  {
    id: "n5",
    position: { x: 1120, y: 60 },
    data: {
      label: "1",
      className: "nodeContent--main",
      style: { minWidth: 120, border: "2px solid #e0a100" },
      handles: [{ id: "in", type: "target", position: Position.Left }],
    },
    type: "customNode",
  },
  {
    id: "n6",
    position: { x: 1120, y: 230 },
    data: {
      label: "0",
      className: "nodeContent--main",
      style: { minWidth: 120, border: "2px solid #e0a100" },
      handles: [{ id: "in", type: "target", position: Position.Left }],
    },
    type: "customNode",
  },
  // {
  //   id: "n7",
  //   position: { x: 260, y: 430 },
  //   data: {
  //     label: "Data",
  //     className: "nodeContent--main",
  //     style: { minWidth: 140 },
  //     handles: [
  //       { id: "out1", type: "source", position: Position.Top, offset: -80 },
  //       { id: "out2", type: "source", position: Position.Top, offset: -20 },
  //       { id: "out3", type: "source", position: Position.Top, offset: 40 },
  //       { id: "out4", type: "source", position: Position.Top, offset: 100 },
  //       { id: "outRight", type: "source", position: Position.Right },
  //     ],
  //   },
  //   type: "customNode",
  // },
  // {
  //   id: "n8",
  //   position: { x: 60, y: 570 },
  //   data: {
  //     label: "Text",
  //     className: "nodeContent--branch",
  //     handles: [{ id: "in", type: "target", position: Position.Top }],
  //   },
  //   type: "customNode",
  // },
  // {
  //   id: "n9",
  //   position: { x: 220, y: 570 },
  //   data: {
  //     label: "Images",
  //     className: "nodeContent--branch",
  //     handles: [{ id: "in", type: "target", position: Position.Top }],
  //   },
  //   type: "customNode",
  // },
  // {
  //   id: "n10",
  //   position: { x: 380, y: 570 },
  //   data: {
  //     label: "Audio",
  //     className: "nodeContent--branch",
  //     handles: [{ id: "in", type: "target", position: Position.Top }],
  //   },
  //   type: "customNode",
  // },
  // {
  //   id: "n11",
  //   position: { x: 540, y: 570 },
  //   data: {
  //     label: "Video",
  //     className: "nodeContent--branch",
  //     handles: [{ id: "in", type: "target", position: Position.Top }],
  //   },
  //   type: "customNode",
  // },
  // {
  //   id: "n12",
  //   position: { x: 560, y: 430 },
  //   data: {
  //     label: "Numbers",
  //     className: "nodeContent--main",
  //     style: { minWidth: 170 },
  //     handles: [
  //       { id: "in", type: "target", position: Position.Left },
  //       { id: "out", type: "source", position: Position.Right },
  //     ],
  //   },
  //   type: "customNode",
  // },
  // {
  //   id: "n13",
  //   position: { x: 860, y: 430 },
  //   data: {
  //     label: "Binary\n(0s and 1s)",
  //     className: "nodeContent--main",
  //     style: { whiteSpace: "pre-line", minWidth: 180 },
  //     handles: [
  //       { id: "in1", type: "target", position: Position.Left },
  //       { id: "in2", type: "target", position: Position.Top },
  //     ],
  //   },
  //   type: "customNode",
  // },
];

export const initialEdges = [
  {
    id: "n1-n2",
    source: "n1",
    target: "n2",
    label: "consists of many",
    markerEnd: { type: "arrowclosed" },
  },
  {
    id: "n2-n3",
    source: "n2",
    sourceHandle: "outTop",
    target: "n3",
    targetHandle: "in",
    label: "can be",
    markerEnd: { type: "arrowclosed" },
  },
  {
    id: "n2-n4",
    source: "n2",
    sourceHandle: "outBottom",
    target: "n4",
    targetHandle: "in",
    label: "or",
    markerEnd: { type: "arrowclosed" },
  },
  {
    id: "n3-n5",
    source: "n3",
    sourceHandle: "out",
    target: "n5",
    targetHandle: "in",
    label: "electricity flows",
    markerEnd: { type: "arrowclosed" },
  },
  {
    id: "n4-n6",
    source: "n4",
    sourceHandle: "out",
    target: "n6",
    targetHandle: "in",
    label: "electricity does not flow",
    markerEnd: { type: "arrowclosed" },
  },
  // {
  //   id: "n8-n12",
  //   source: "n8",
  //   target: "n12",
  //   label: "represented by",
  //   markerEnd: { type: "arrowclosed" },
  // },
  // {
  //   id: "n9-n12",
  //   source: "n9",
  //   target: "n12",
  //   label: "",
  //   markerEnd: { type: "arrowclosed" },
  // },
  // {
  //   id: "n10-n12",
  //   source: "n10",
  //   target: "n12",
  //   label: "",
  //   markerEnd: { type: "arrowclosed" },
  // },
  // {
  //   id: "n11-n12",
  //   source: "n11",
  //   target: "n12",
  //   label: "",
  //   markerEnd: { type: "arrowclosed" },
  // },
  // {
  //   id: "n12-n13",
  //   source: "n12",
  //   target: "n13",
  //   label: "converted to",
  //   markerEnd: { type: "arrowclosed" },
  // },
  // {
  //   id: "n7-n13",
  //   source: "n7",
  //   sourceHandle: "outRight",
  //   target: "n13",
  //   targetHandle: "in2",
  //   label: "stored as",
  //   markerEnd: { type: "arrowclosed" },
  // },
];
